### ISSUE TITLE
Create/Update Documentation

### ISSUE THREAD

**Issue by having11** [SubZero-Robotics/2024-CommandRobot#11]
- [x] 2024-CommandRobot README with similar information as the 2023 repo
- [x] Software architecture diagram (main components and flow)
- [x] Network diagram (anything that communicates via Ethernet or WiFi with the RIO)
- [x] Hardware diagram (microprocessors and microcontrollers)
- [x] README file describing robot code
- [x] Document Subsystems
- [x] #58
- [x] #59
- [x] #61

**Comment by nobody5050** [comment]
Reopening with larger scope for documenting new code
