### ISSUE TITLE
Whitepaper Summary

### ISSUE THREAD

**Issue by having11** [SubZero-Robotics/2024-CommandRobot#144]
Create a whitepaper that describes the advanced portions of our code/process/hardware.

Some topics to consider:

- State, Triggers, etc.
- Advanced command compositions
- Using on-the-fly pathplanner for fully autonomous operation
- Connector X
- Base Single Axis v2
- Usage of GitHub/version control
- Pose estimation and vision/note aiming
- Safety features (how did we idiot-proof everything?)

**Comment by nobody5050** [comment]
- turn to angle, turn to pose
- auto chooser

**Comment by having11** [comment]
https://www.chiefdelphi.com/t/whitepaper-subzero-robotics-2024-software-recap/467817
