### ISSUE TITLE
Add calls to ChassisSpeeds.discretize()

### ISSUE THREAD

**Issue by habig** [SubZero-Robotics/2024-CommandRobot#74]
Swerve drives tend to drift as they rotate.  Here's a [great discussion](https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964).

A fix is part of the [2024 WpiLib](https://docs.wpilib.org/en/stable/docs/yearly-overview/yearly-changelog.html), in the `discretize()` method to the `ChassisSpeeds` object we're already using.

Levi had implemented this in on the test robot, but removed it when he encountered a bug where the first loop didn't have a good delta-t set in some cases.  That's easily fixed with a default value.

It would be good to get this back in before people really get used to the "feel" of how the robot currently drives: it brings along less drift and more precision, but we want the driving to be set soon so all this practice time we have before LSR can really pay off.

**Comment by habig** [comment]
This worked - the needed small code change is in the drive laptop and worked as advertised, but needs commited back to git.

**Comment by nobody5050** [comment]
Before we close we should update this to track the previous loop time
